### ISSUE TITLE
ERR: lws_context_init_server_ssl: SSL_CTX_load_verify_locations unhappy

### ISSUE THREAD

**Issue by frenck** [hassio-addons/addon-terminal#1]
## Problem/Motivation

The following error is displayed in the logs of the add-on:

> ERR: lws_context_init_server_ssl: SSL_CTX_load_verify_locations unhappy

The add-on, however, functions perfectly.

## Proposed changes

Find out of this error can be fixed or suppressed.
At least add it to the documentation as a known error.

**Comment by Aephir** [comment]
I get the same error in the log.

`ERR: lws_context_init_server_ssl: SSL_CTX_load_verify_locations unhappy`

And here, the terminal doesn't load. I get an error stating that: "HASS unexpectedly closed the connection", regardless of whether I use the panel or through browser.

My options:
```
{
  "debug": false,
  "username": "####",
  "password": "####",
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "packages": [],
  "init_commands": []
}
```

**Comment by frenck** [comment]
@Aephir That has nothing to do with this error message.
You have enabled SSL, ensure you are using HTTPS:// everywhere (including the iframe panel you've added to your configuration of Home Assistant).

**Comment by Aephir** [comment]
@frenck Thanks, but I am using https:// for everything (both when trying https://MYSUPERSECRET.DUCKDNS.org:7681 in browser, and url in the panel). 

Is it that I can't access it via dns? I didn't try just https://192.168.0.XX:7681 when at home.

**Comment by frenck** [comment]
Notice has been added to the documentation.
Closing this issue.
