### ISSUE TITLE
Terminal does not start, with SSL enabled

### ISSUE THREAD

**Issue by cogneato** [hassio-addons/addon-terminal#13]
# Problem/Motivation

> Terminal will not load/start

## Expected behavior

> Terminal starts normally

## Actual behavior

> After starting the add on, refreshing logs shows repeating "INFO: Starting the ttyd daemon"

## Steps to reproduce

> Start Terminal addon, refresh logs
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Confirmed, as discussed / determined on Discord, this issue only occurs when having SSL enabled.

**Comment by frenck** [comment]
Fixed in v2.0.1.

Thanks for the report @cogneato!
