### ISSUE TITLE
Raspberry Pi3 reseting when installing from local addons

### ISSUE THREAD

**Issue by androiddrew** [hassio-addons/addon-terminal#17]
I would like to add a external usb hard drive to my home assistant to expand the SMB share. I am attempting to install this addon under my local addons for Home assistant 0.60 running on a Raspberry Pi using the hassio image. I have found that this can't be done directly via SSH, but I have come across [this forum thread](https://community.home-assistant.io/t/how-do-i-view-the-usb-devices-with-hass-io/22807/17) which describes modifying the config.json file of this addon to grant access to the attached block device, allowing me to mount it. 

I have git cloned the repo, added the described lines in the config, and uploaded to my local addons folder. When I go into the hassio store and try to install the addon, my device appears to reset. I have attempted to install this multiple times without success. I can not find anything in the logs either that explains what issue is being encountered.

**Comment by frenck** [comment]
The method in that thread is not supported by this add-on.
