### ISSUE TITLE
SSL Error - but still working as expected

### ISSUE THREAD

**Issue by dkmaker** [hassio-addons/addon-terminal#20]
# Problem/Motivation

I wanted to enable SSL - i have a cert from Geotrust, and i use it for all other services on HASS

## Expected behavior

No issues in the logfile regarding SSL Certificate

## Actual behavior

I get this error in the logfile

INFO: Starting the ttyd daemon
[2018/04/19 10:48:04:5775] ERR: lws_context_init_server_ssl: SSL_CTX_load_verify_locations unhappy
[2018/04/19 10:48:04:5814] ERR: Unable to load SSL Client certs file from (null) -- client ssl isn't going to work

Then when this error is reproduced then it seems like the Terminal is somehow stuck restarting the terminal module will make it work again.

## Steps to reproduce

Restart the service - it will fire everytime, and when i remove the SSL it stops but iFrame with SSL/NON SSL is not good in chrome etc.

**Comment by dkmaker** [comment]
Did not read the README to the end - Closing the case my self.. :) Sorry for the bummer

**Comment by frenck** [comment]
No problem :)
