### ISSUE TITLE
Directory `/addons` does not appear mapped

### ISSUE THREAD

**Issue by dcmartin** [hassio-addons/addon-terminal#6]
## Problem/Motivation

Installation of HASSIO using generic LINUX installation; access to homeassistant container using docker CLI `docker exec -it homeassistant bash` provides visibility into /addons, /config and other directories; updates copied from host (VM) to /config are represented when accessing homeassistant using terminal addon; do not see changes to directory /addons

## Expected behavior

Expected to see /addons populated with directories/files copied using `docker cp`

## Actual behavior

Saw files copied using `docker cp` for the /config directory, but not the /addons directory.

## Steps to reproduce

Install hassio on LINUX host (VM); add-on terminal; connect to homeassistant; inspect /config and /addons for content; make changes to /config and /addons using `docker` CLI from host; utilize terminal to inspect directories; see changes reflected in /config, but not /addons.

## Proposed changes

> (If you have a proposed change, workaround or fix, describe the rationale behind it)

**Comment by frenck** [comment]
@dcmartin 

The docker CLI you've provided will get you into the 'homeassistant' container, which is not the terminal container. Quite possibly the 'homeassistant' container does not mount / have access to the 'addons' folder.

This terminal addon, however, does have a mapping to the 'addons' folder:

https://github.com/hassio-addons/addon-terminal/blob/f93fdfd91d52c50302fc7a08248aec86ff3b3fc7/terminal/config.json#L18
